{{- range $app := .Values.applications }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $app.type }}-{{ $app.name }}-cm
  namespace: {{ $.Values.environment }}-{{ $.Values.projectName }}
  labels:
    {{- include "generic-app.labels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "app" $app "component" "configmap") | nindent 4 }}
  annotations:
    {{- include "generic-app.configMapAnnotations" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "app" $app) | nindent 4 }}
data:
  placeholder: ""
{{- range $key, $value := $app.configs }}
  {{ $key }}: {{ quote $value }}
{{- end }}
---
{{- end}}
