{{- range $app := .Values.applications}}
{{- if or (not (hasKey $app "hpa")) ($app.hpa.enabled)}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{$app.type}}-{{$app.name}}-hpa
  namespace: {{$.Values.environment}}-{{$.Values.projectName}}
  labels:
    {{- include "generic-app.labels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "app" $app "component" "hpa") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{$app.type}}-{{$app.name}}
  minReplicas: {{$app.replicas | default 1}}
  maxReplicas: {{(($app.hpa | default dict).maxReplicas | default $.Values.defaults.hpa.maxReplicas)}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{(($app.hpa | default dict).targetCPUUtilizationPercentage | default $.Values.defaults.hpa.targetCPUUtilizationPercentage)}}
---
{{- end}}
{{- end}}
