{{- range $app := .Values.applications}}
{{- range .secrets}}
{{- $secret := . }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-external-secret
  namespace: {{ $.Values.environment }}-{{ $.Values.projectName }}
  labels:
    secret.kubernetes.io/type: "external-secret"
    app: {{ $app.name }}
    {{- include "generic-app.labels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "app" $app "component" "external-secret") | nindent 4 }}
  annotations:
    {{- include "generic-app.externalSecretsAnnotations" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "app" $app) | nindent 4 }}
spec:
  refreshInterval: 90s

  secretStoreRef:
    name: aws-secrets-manager-cluster-store
    kind: ClusterSecretStore

  target:
    name: {{ .name }}
    creationPolicy: Owner
  {{- if .keys }}
  data:
    {{- range .keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $secret.path }}
        property: {{ . }}
    {{- end }}
  {{- else }}
  dataFrom:
    - extract:
        key: {{ .path }}
  {{- end }}
---
{{- end }}
{{- end }}
