apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-service-account
  namespace: "{{ $.Values.environment }}-{{ $.Values.projectName }}"
  labels:
    {{- include "generic-app.labels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "component" "ecr-service-account") | nindent 4 }}
  annotations:
    {{- include "generic-app.serviceAccountAnnotations" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values) | nindent 4 }}
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws.accountId }}:role/{{ $.Values.environment }}-{{ $.Values.projectName }}-ecr-role"
{{- range $app := .Values.applications }}
{{- if $app.awsRole }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $app.type }}-{{ $app.name }}-sa
  namespace: "{{ $.Values.environment }}-{{ $.Values.projectName }}"
  labels:
    {{- include "generic-app.labels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "app" $app "component" "service-account") | nindent 4 }}
  annotations:
    {{- include "generic-app.serviceAccountAnnotations" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values) | nindent 4 }}
    eks.amazonaws.com/role-arn: {{ $app.awsRole }}
{{- end }}
{{- end }}
